flask-mongo:
  build: .
  ports:
    - "5000:5000"
  volumes:
    - "/proc:/proc"
  nertwork_mode: host
  depends_on:
    - mongo

mongo:
  image: mongo
  ports:
    - "27017:27017"
  expose:
    - "27017"
  nertwork_mode: host